In [1]:
import os 
import glob
import numpy as np
import pandas as pd
import importlib as imp

from tqdm import tqdm, tqdm_notebook
import warnings
warnings.simplefilter('ignore')
pd.options.display.max_columns = 100

*Ваша третья лабораторная работа будет заключаться в реализации и сравнении алгоритмов для решения quadratic assignment problem. Вам нужно будет реализовать следующие алгоритмы, которые мы разбирали на паре:*

**1) Local search - сделать 2 opt либо с best-improvement либо first-improvement + don't look bits<br>
2) Iterated local search - можно использовать stochastic 2-opt <br>
3) Guided local search  - можно использовать stochastic 2-opt <br>**

Реализовать можно на любом языке. Также нужно будет сравнить время работы алгоритма, а так же показать лучшее решение каждого алгоритма, которое удалось найти вам.

---

<i>**Данные:**

Данные для работы прикрепил архивом к письму. Структура такая: <br>
n - количество заводов и мест <br>
следующие n строчек - матрица расстояний D <br>
пустая строчка <br>
следующие n строчек - матрица потока F</i>

---

Форма отчетности: <br>

Вы присылаете мне код алгоритмов и небольшой отчет. Пожалуйста прикрепляте код в отдельном исполняймом файле, не засовывайте в отчет. Работать можно в группах не более 3-х человек. В отчете должны быть таблички со скоростью и для конкретного алгоритма на конкретном наборе данных + ответ каждого алгоритма.

**Важно:** сделайте так же файлики с ответами. Имя файлика - Tai20a.sol, Tai40a.sol  и т.п. Формат файлика с ответами:

14 13 5... - значит завод 14 помещаем на 1 локацию, 13 на 2, 5 на 3 и т.п. Разделитель пробел.

In [9]:
from utils import tools
tools = imp.reload(tools)

In [3]:
benchmarks = glob.glob('data/*')
benchmarks

['data\\tai100a',
 'data\\tai20a',
 'data\\tai40a',
 'data\\tai60a',
 'data\\tai80a']

In [89]:
from algorithm import local_search, iterated_local_search, guided_local_search
tools   = imp.reload(tools)
problem = tools.get_problem_dct(benchmarks[1])
# print(problem)
print('{} items'.format(problem['n']))

solution = np.arange(problem['n'])
solution = np.random.permutation(solution)
cur_cost = tools.compute_solution(problem, solution)
print('Start cost {}'.format(cur_cost))

20 items
Start cost 904234


In [90]:
%%time
local_search = imp.reload(local_search)

params = dict(solution=solution,
              method='first-improvement',
              n_iter=100,
              verbose=True)
alg = local_search.LocalSearch(problem)
alg.set_params(params)
alg.solve()

Start cost 904234


 19%|██████████████▋                                                              | 19/100 [00:00<00:00, 181.45it/s]

No better solutions, stoping...


End cost 774714
Wall time: 201 ms


array([ 9,  7,  5, 19,  6, 14, 10, 13,  4, 16, 18, 12,  8, 17,  3,  2,  1,
       11,  0, 15])

In [91]:
iterated_local_search = imp.reload(iterated_local_search)
params = dict(solution=solution,
              method='first-improvement',
              n_iter_ls=200,
              n_iter=100,
              verbose=True)
alg = iterated_local_search.Iterated(problem)
alg.set_params(params)
alg.refresh_params()
alg.solve()

100%|█████████████████████████████████████████████████████████████████████████████| 100/100 [00:31<00:00,  3.21it/s]


End cost: 732018


array([ 8, 17, 10,  2, 13, 12,  1, 16,  7, 11, 18, 15,  4,  3,  0, 14,  5,
        6,  9, 19])

In [92]:
guided_local_search = imp.reload(guided_local_search)
params = dict(solution=solution,
              method='first-improvement',
              n_iter=200,
              n_epoch=100,
              mu=2,
              verbose=True)
alg = guided_local_search.Guided(problem)
alg.set_params(params)
alg.refresh_params()
alg.solve()

100%|█████████████████████████████████████████████████████████████████████████████| 100/100 [00:27<00:00,  3.68it/s]


End cost: 741130.0


array([ 3,  7,  5, 19, 16,  4, 14, 13, 18,  6, 10, 12,  8,  9, 17,  2,  1,
       11,  0, 15])